### ISSUE TITLE
Lista parcial de páginas revisadas e sem erros.

### ISSUE THREAD

**Issue by brunomonteiro3** [zenorocha/diveintohtml5#44]
Revisei algumas páginas e não encontrei erros. São elas:
- everything.html
- legal.html
- about.html *

*: O endereço mark[at]diveintomark[dot]org não existe mais. Seria interessante remover e inserir um e-mail válido de alguém da equipe de tradução/revisão?
## 

Dei commit em 2 arquivos (forms.html & table-of-contents.html), mas tenho outros prontos. Tive alguns problemas com o GitHub e por isso mandei em partes, amanhã envio os outros arquivos revisados.

**Comment by zenorocha** [comment]
Beleza @brunomonteiro3, aproveitei para atualizar o [wiki de Revisão](https://github.com/zenorocha/diveintohtml5/wiki/Revis%C3%A3o). 

Pode conferir se está certo o que coloquei por lá?

**Comment by brunomonteiro3** [comment]
É isso mesmo @zenorocha. :) 

Vou ver se faço a revisão dos itens restantes ainda hoje!

**Comment by zenorocha** [comment]
Em `about`, troquei para o meu endereço de email. Realmente não faz sentido apontar para o Mark, já que sumiu da web.
