### ISSUE TITLE
Status da tradução

### ISSUE THREAD

**Issue by thiagopnts** [zenorocha/diveintohtml5#55]
Ainda falta alguma página para ser traduzida?

**Comment by zenorocha** [comment]
Falta apenas uma página =D
- Para ver o status da tradução, confira a [Wiki de Tradução](https://github.com/zenorocha/diveintohtml5/wiki/Tradu%C3%A7%C3%A3o)
- Para ver o status da tradução, confira a [Wiki de Revisão](https://github.com/zenorocha/diveintohtml5/wiki/Revisão)

**Comment by thiagopnts** [comment]
Só ta faltando a página de web workers né? Vou pegar ela então :)

**Comment by zenorocha** [comment]
Na verdade essa página não foi escrita pelo autor

**Comment by thiagopnts** [comment]
Mas é pra ser traduzida também? Fora ela qual está faltando?

**Comment by zenorocha** [comment]
Não precisa traduzir ela porque não foi escrita pelo autor. Fora ela só falta a página de vídeo que está sendo feita pela Anna. Logo, só sobra a revisão. Existem duas páginas por lá que precisam desse tipo de contribuição.
