### ISSUE TITLE
Link errado

### ISSUE THREAD

**Issue by felquis** [zenorocha/diveintohtml5#59]
Estava lendo http://diveintohtml5.com.br/semantics.html até que em **O doctype** no fim do terceiro paragrafo, tem o link para _"o modo quase padronizado (almost standards mode)."_ porém não consigo abrir o link de nenhuma maneira.

https://developer.mozilla.org/en/Gecko's_%22Almost_Standards%22_Mode

https://developer.mozilla.org/en-US/docs/Gecko%27s_%22Almost_Standards%22_Mode

Alguma dica?

**Comment by thiagopnts** [comment]
Parece que o endereço mudou no site da mozilla mesmo, pq esse link tbm não funciona na página original. Você não ta conseguindo acessar nem esse segundo link? Esse ta abrindo de boa aqui, parece ser a URL atual.

**Comment by henriquelbsouza** [comment]
Aqui abriu os dois...
"Gecko's "Almost Standards" Mode"

**Comment by felquis** [comment]
Deve ser algum problema no meu PC =/ o chrome coloca uns caracteres como _' "_ na url e não abre a pagina corretamente.

**Comment by zenorocha** [comment]
estranho, aqui rolou direitinho também
