### ISSUE TITLE
Erro ao mostrar uma tag

### ISSUE THREAD

**Issue by marcelod** [zenorocha/diveintohtml5#62]
Na página http://diveintohtml5.com.br/past.html imagino ter um erro ao exibir a tag < ht / > onde deveria ser < hr / >

Segue o paragrafo

"Até hoje, milhões de páginas da internet dizem ser XHTML; Elas começam com o doctype XHTML na primeira linha, usam tags com caixa baixa, usam aspas nos atributos e uma barra simples ao final de elementos vazios como < br / > e < ht / >; Mas uma pequena fração dessas páginas são realmente servidas com o MIME type application/xhtml+xml e que façam o tratamento de erro draconiano. Qualquer página que possua o MIME type text/html — independente do doctype, sintaxe ou estilo de código — será interpretada usando um parseador HTML tolerante, que silenciosamente ignorará qualquer erro de marcação e nunca alertará os usuários finals (ou qualquer outra pessoa) se a página está tecnicamente quebrada;"

**Comment by zenorocha** [comment]
obrigado @marcelod por avisar e @thiagopnts por corrigir =D
