### ISSUE TITLE
Versão PDF

### ISSUE THREAD

**Issue by cassionandi** [zenorocha/diveintohtml5#71]
Olá.

É possível gerar uma versão PDF desse projeto a partir de algum comando?

**Comment by zenorocha** [comment]
Oi @cassionandi, tem a opção do ePub, serve?

http://readlists.com/6d1a2c53/

**Comment by cassionandi** [comment]
Grande @zenorocha, essa versão ePub está ótima. Muito agradecido, e parabéns pelo nome (Zeno), muito estiloso (sério).

**Comment by cassionandi** [comment]
@zenorocha, imprimindo uma página do ePub, notei que a página fica sem margens. Você tem alguma recomendação para adicionar margens a esquerda do livro? Estou usando o Calibre para visualizar o arquivo.

**Comment by cassionandi** [comment]
@zenorocha meu mestre, resolvido utilizando a configuração de página (page setup) do próprio Calibri. Obrigado novamente!
