### ISSUE TITLE
Ortografia no detect.html

### ISSUE THREAD

**Issue by ghost** [zenorocha/diveintohtml5#82]
Olá caros,

No arquivo detect.html, na linha 483, ao tratar do auto focus, acredito que a palavra correta seja "comportamento" ao invés de "comportamente".

abç, e vida longa ao projeto!

**Comment by zenorocha** [comment]
Show de bola, pode mandar um pull request @ghtp25?

**Comment by ghost** [comment]
Pull request feito.
